In [1]:
print("jupyter is working")

jupyter is working

In [2]:
4+4

8

In [3]:
5+5

10

In [4]:
9+9

18

In [5]:
pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.2)
Requirement already satisfied: matplotlib in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("Fitness_Health_Tracking_Dataset.csv")
df.head()

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,01-01-2023 00:00,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,02-01-2023 00:00,19,Female,191,80,7010,1806,NaN,3.103590,47.0,72.0,Cardio,9,Neutral
2,1,Sara Martinez,03-01-2023 00:00,19,Female,191,80,18942,2274,8.167817,3.814843,46.0,85.0,Yoga,6,Sad
3,1,Sara Martinez,04-01-2023 00:00,19,Female,191,80,13778,2656,7.453552,3.508636,105.0,77.0,Yoga,2,Sad
4,1,Sara Martinez,05-01-2023 00:00,19,Female,191,80,10247,3571,5.132654,NaN,53.0,61.0,Yoga,8,Sad

## View First 5 Rows

In [8]:
df.head(5)

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,01-01-2023 00:00,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,02-01-2023 00:00,19,Female,191,80,7010,1806,NaN,3.103590,47.0,72.0,Cardio,9,Neutral
2,1,Sara Martinez,03-01-2023 00:00,19,Female,191,80,18942,2274,8.167817,3.814843,46.0,85.0,Yoga,6,Sad
3,1,Sara Martinez,04-01-2023 00:00,19,Female,191,80,13778,2656,7.453552,3.508636,105.0,77.0,Yoga,2,Sad
4,1,Sara Martinez,05-01-2023 00:00,19,Female,191,80,10247,3571,5.132654,NaN,53.0,61.0,Yoga,8,Sad

## View Last 5 Rows

In [9]:
df.tail(5)

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
36495,100,Sara Jones,27-12-2023 00:00,54,Male,151,107,10905,3922,NaN,2.781033,61.0,96.0,NaN,3,Sad
36496,100,Sara Jones,28-12-2023 00:00,54,Male,151,107,2245,3151,7.652822,NaN,93.0,74.0,NaN,10,Happy
36497,100,Sara Jones,29-12-2023 00:00,54,Male,151,107,11892,2906,7.173268,3.237390,43.0,67.0,Cardio,9,Happy
36498,100,Sara Jones,30-12-2023 00:00,54,Male,151,107,12967,1863,4.011179,3.650197,85.0,61.0,Yoga,4,Happy
36499,100,Sara Jones,31-12-2023 00:00,54,Male,151,107,14667,2513,6.652888,3.199435,108.0,66.0,NaN,8,Sad

## Dataset Shape

In [10]:
df.shape

(36500, 16)

## Column Names

In [11]:
df.columns

Index(['User_ID', 'Full Name', 'Date', 'Age', 'Gender', 'Height (cm)',
       'Weight (kg)', 'Steps_Taken', 'Calories_Burned', 'Hours_Slept',
       'Water_Intake (Liters)', 'Active_Minutes', 'Heart_Rate (bpm)',
       'Workout_Type', 'Stress_Level (1-10)', 'Mood'],
      dtype='str')

## Dataset Information

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   36500 non-null  str
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            32841 non-null  float64
 10  Water_Intake (Liters)  31099 non-null  float64
 11  Active_Minutes         34633 non-null  float64
 12  Heart_Rate (bpm)       34668 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: float64(4), int64(7), str(5)
memory usage: 4.5 MB

## Statistical Summary

In [13]:
df.describe()

,User_ID,Age,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Stress_Level (1-10)
count,36500.000000,36500.000000,36500.000000,36500.000000,36500.000000,36500.000000,32841.000000,31099.000000,34633.000000,34668.000000,36500.000000
mean,50.500000,43.160000,172.690000,85.830000,11035.111973,2747.735452,6.492194,2.742529,74.372477,79.574305,5.499260
std,28.866465,13.674046,14.433974,21.567426,5203.268097,723.854309,1.437658,0.720265,26.012433,11.532934,2.881435
min,1.000000,19.000000,150.000000,51.000000,2000.000000,1500.000000,4.000329,1.500416,30.000000,60.000000,1.000000
25%,25.750000,29.000000,160.000000,68.000000,6522.750000,2119.000000,5.239025,2.121126,52.000000,70.000000,3.000000
50%,50.500000,44.000000,173.000000,86.000000,11042.000000,2748.000000,6.500790,2.739198,74.000000,80.000000,6.000000
75%,75.250000,56.250000,181.000000,107.000000,15561.500000,3376.000000,7.732830,3.363530,97.000000,90.000000,8.000000
max,100.000000,63.000000,199.000000,118.000000,19999.000000,3999.000000,8.999341,3.999981,119.000000,99.000000,10.000000

## Checking Missing Values
This step checks the number of missing values in each column of the dataset.

In [14]:
df.isnull().sum()

User_ID                     0
Full Name                   0
Date                        0
Age                         0
Gender                      0
Height (cm)                 0
Weight (kg)                 0
Steps_Taken                 0
Calories_Burned             0
Hours_Slept              3659
Water_Intake (Liters)    5401
Active_Minutes           1867
Heart_Rate (bpm)         1832
Workout_Type             9192
Stress_Level (1-10)         0
Mood                        0
dtype: int64

In [15]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [16]:
df.head(2)

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,2023-01-01,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,2023-02-01,19,Female,191,80,7010,1806,NaN,3.103590,47.0,72.0,Cardio,9,Neutral

In [17]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=True)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   14400 non-null  datetime64[us]
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            32841 non-null  float64
 10  Water_Intake (Liters)  31099 non-null  float64
 11  Active_Minutes         34633 non-null  float64
 12  Heart_Rate (bpm)       34668 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: datetime64[us](1), float64(4), int64(7), str(4)
memory usage: 4.5 MB

In [19]:
df.numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
df.numeric_columns

C:\Users\Dell\AppData\Local\Temp\ipykernel_9276\2134220839.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()

['User_ID',
 'Age',
 'Height (cm)',
 'Weight (kg)',
 'Steps_Taken',
 'Calories_Burned',
 'Hours_Slept',
 'Water_Intake (Liters)',
 'Active_Minutes',
 'Heart_Rate (bpm)',
 'Stress_Level (1-10)']

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   14400 non-null  datetime64[us]
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            32841 non-null  float64
 10  Water_Intake (Liters)  31099 non-null  float64
 11  Active_Minutes         34633 non-null  float64
 12  Heart_Rate (bpm)       34668 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: datetime64[us](1), float64(4), int64(7), str(4)
memory usage: 4.5 MB

In [21]:
df.groupby("User_ID")[[
    "Hours_Slept",
    "Water_Intake (Liters)",
    "Active_Minutes",
    "Heart_Rate (bpm)"
]].apply(lambda x: x.isnull().sum())

         Hours_Slept  Water_Intake (Liters)  Active_Minutes  Heart_Rate (bpm)
User_ID
1                 37                     47              19                22
2                 43                     59              19                12
3                 40                     53              18                18
4                 35                     61              20                15
5                 46                     55              22                20
...              ...                    ...             ...               ...
96                31                     45              16                20
97                30                     66              19                19
98                36                     52              21                23
99                40                     49              23                15
100               34                     64              31                21

[100 rows x 4 columns]

In [22]:
numeric_cols = [
    "Hours_Slept",
    "Water_Intake (Liters)",
    "Active_Minutes",
    "Heart_Rate (bpm)"
]
df[numeric_cols] = df.groupby("User_ID")[numeric_cols].transform(
    lambda x: x.interpolate(method="linear")
)

In [23]:
df.isnull().sum()

User_ID                      0
Full Name                    0
Date                     22100
Age                          0
Gender                       0
Height (cm)                  0
Weight (kg)                  0
Steps_Taken                  0
Calories_Burned              0
Hours_Slept                  8
Water_Intake (Liters)       10
Active_Minutes               6
Heart_Rate (bpm)             5
Workout_Type              9192
Stress_Level (1-10)          0
Mood                         0
dtype: int64

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   14400 non-null  datetime64[us]
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            36492 non-null  float64
 10  Water_Intake (Liters)  36490 non-null  float64
 11  Active_Minutes         36494 non-null  float64
 12  Heart_Rate (bpm)       36495 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: datetime64[us](1), float64(4), int64(7), str(4)
memory usage: 4.5 MB

In [25]:
df[numeric_cols] = df.groupby("User_ID")[numeric_cols].transform(
    lambda x: x.ffill().bfill()
)

In [26]:
df[numeric_cols] = df.groupby("User_ID")[numeric_cols].transform(
    lambda x: x.ffill().bfill()
)

In [27]:
9222+9048+9038-36500

-9192

In [28]:
df["Workout_Type"] = df["Workout_Type"].fillna("No Workout")

In [29]:
df.head()

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,2023-01-01,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,2023-02-01,19,Female,191,80,7010,1806,7.594509,3.103590,47.0,72.0,Cardio,9,Neutral
2,1,Sara Martinez,2023-03-01,19,Female,191,80,18942,2274,8.167817,3.814843,46.0,85.0,Yoga,6,Sad
3,1,Sara Martinez,2023-04-01,19,Female,191,80,13778,2656,7.453552,3.508636,105.0,77.0,Yoga,2,Sad
4,1,Sara Martinez,2023-05-01,19,Female,191,80,10247,3571,5.132654,2.576740,53.0,61.0,Yoga,8,Sad

In [30]:
import pandas as pd

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   14400 non-null  datetime64[us]
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            36500 non-null  float64
 10  Water_Intake (Liters)  36500 non-null  float64
 11  Active_Minutes         36500 non-null  float64
 12  Heart_Rate (bpm)       36500 non-null  float64
 13  Workout_Type           36500 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: datetime64[us](1), float64(4), int64(7), str(4)
memory usage: 4.5 MB

In [33]:
df.isnull().sum()

User_ID                      0
Full Name                    0
Date                     22100
Age                          0
Gender                       0
Height (cm)                  0
Weight (kg)                  0
Steps_Taken                  0
Calories_Burned              0
Hours_Slept                  0
Water_Intake (Liters)        0
Active_Minutes               0
Heart_Rate (bpm)             0
Workout_Type                 0
Stress_Level (1-10)          0
Mood                         0
dtype: int64

In [36]:
df.isnull().sum()

User_ID                      0
Full Name                    0
Date                     22100
Age                          0
Gender                       0
Height (cm)                  0
Weight (kg)                  0
Steps_Taken                  0
Calories_Burned              0
Hours_Slept                  0
Water_Intake (Liters)        0
Active_Minutes               0
Heart_Rate (bpm)             0
Workout_Type                 0
Stress_Level (1-10)          0
Mood                         0
dtype: int64